package org.fantasy.league.dota2.core.common

sealed class Heroes(
    val id: Int,
    val name: String
) {
    object AntiMage: Heroes(1, "Anti-Mage")
    object Axe: Heroes(2, "Axe")
    object Bane: Heroes(3, "Bane")
    object Bloodseeker: Heroes(4, "Bloodseeker")
    object CrystalMaiden: Heroes(5, "Crystal Maiden")
    object DrowRanger: Heroes(6, "Drow Ranger")
    object Earthshaker: Heroes(7, "Earthshaker")
    object Juggernaut: Heroes(8, "Juggernaut")
    object Mirana: Heroes(9, "Mirana")
    object Morphling: Heroes(10, "Morphling")
    object ShadowFiend: Heroes(11, "Shadow Fiend")
    object PhantomLancer: Heroes(12, "Phantom Lancer")
    object Puck: Heroes(13, "Puck")
    object Pudge: Heroes(14, "Pudge")
    object Razor: Heroes(15, "Razor")
    object SandKing: Heroes(16, "Sand King")
    object StormSpirit: Heroes(17, "Storm Spirit")
    object Sven: Heroes(18, "Sven")
    object Tiny: Heroes(19, "Tiny")
    object VengefulSpirit: Heroes(20, "Vengeful Spirit")
    object Windranger: Heroes(21, "Windranger")
    object Zeus: Heroes(22, "Zeus")
    object Kunkka: Heroes(23, "Kunkka")
    object Lina: Heroes(25, "Lina")
    object Lion: Heroes(26, "Lion")
    object ShadowShaman: Heroes(27, "Shadow Shaman")
    object Slardar: Heroes(28, "Slardar")
    object Tidehunter: Heroes(29, "Tidehunter")
    object WitchDoctor: Heroes(30, "Witch Doctor")
    object Lich: Heroes(31, "Lich")
    object Riki: Heroes(32, "Riki")
    object Enigma: Heroes(33, "Enigma")
    object Tinker: Heroes(34, "Tinker")
    object Sniper: Heroes(35, "Sniper")
    object Necrophos: Heroes(36, "Necrophos")
    object Warlock: Heroes(37, "Warlock")
    object Beastmaster: Heroes(38, "Beastmaster")
    object QueenOfPain: Heroes(39, "Queen of Pain")
    object Venomancer: Heroes(40, "Venomancer")
    object FacelessVoid: Heroes(41, "Faceless Void")
    object WraithKing: Heroes(42, "Wraith King")
    object DeathProphet: Heroes(43, "Death Prophet")
    object PhantomAssassin: Heroes(44, "Phantom Assassin")
    object Pugna: Heroes(45, "Pugna")
    object TemplarAssassin: Heroes(46, "Templar Assassin")
    object Viper: Heroes(47, "Viper")
    object Luna: Heroes(48, "Luna")
    object DragonKnight: Heroes(49, "Dragon Knight")
    object Dazzle: Heroes(50, "Dazzle")
    object Clockwerk: Heroes(51, "Clockwerk")
    object Leshrac: Heroes(52, "Leshrac")
    object NatureSProphet: Heroes(53, "Nature's Prophet")
    object Lifestealer: Heroes(54, "Lifestealer")
    object DarkSeer: Heroes(55, "Dark Seer")
    object Clinkz: Heroes(56, "Clinkz")
    object Omniknight: Heroes(57, "Omniknight")
    object Enchantress: Heroes(58, "Enchantress")
    object Huskar: Heroes(59, "Huskar")
    object NightStalker: Heroes(60, "Night Stalker")
    object Broodmother: Heroes(61, "Broodmother")
    object BountyHunter: Heroes(62, "Bounty Hunter")
    object Weaver: Heroes(63, "Weaver")
    object Jakiro: Heroes(64, "Jakiro")
    object Batrider: Heroes(65, "Batrider")
    object Chen: Heroes(66, "Chen")
    object Spectre: Heroes(67, "Spectre")
    object AncientApparition: Heroes(68, "Ancient Apparition")
    object Doom: Heroes(69, "Doom")
    object Ursa: Heroes(70, "Ursa")
    object SpiritBreaker: Heroes(71, "Spirit Breaker")
    object Gyrocopter: Heroes(72, "Gyrocopter")
    object Alchemist: Heroes(73, "Alchemist")
    object Invoker: Heroes(74, "Invoker")
    object Silencer: Heroes(75, "Silencer")
    object OutworldDestroyer: Heroes(76, "Outworld Destroyer")
    object Lycan: Heroes(77, "Lycan")
    object Brewmaster: Heroes(78, "Brewmaster")
    object ShadowDemon: Heroes(79, "Shadow Demon")
    object LoneDruid: Heroes(80, "Lone Druid")
    object ChaosKnight: Heroes(81, "Chaos Knight")
    object Meepo: Heroes(82, "Meepo")
    object TreantProtector: Heroes(83, "Treant Protector")
    object OgreMagi: Heroes(84, "Ogre Magi")
    object Undying: Heroes(85, "Undying")
    object Rubick: Heroes(86, "Rubick")
    object Disruptor: Heroes(87, "Disruptor")
    object NyxAssassin: Heroes(88, "Nyx Assassin")
    object NagaSiren: Heroes(89, "Naga Siren")
    object KeeperOfTheLight: Heroes(90, "Keeper of the Light")
    object Io: Heroes(91, "Io")
    object Visage: Heroes(92, "Visage")
    object Slark: Heroes(93, "Slark")
    object Medusa: Heroes(94, "Medusa")
    object TrollWarlord: Heroes(95, "Troll Warlord")
    object CentaurWarrunner: Heroes(96, "Centaur Warrunner")
    object Magnus: Heroes(97, "Magnus")
    object Timbersaw: Heroes(98, "Timbersaw")
    object Bristleback: Heroes(99, "Bristleback")
    object Tusk: Heroes(100, "Tusk")
    object SkywrathMage: Heroes(101, "Skywrath Mage")
    object Abaddon: Heroes(102, "Abaddon")
    object ElderTitan: Heroes(103, "Elder Titan")
    object LegionCommander: Heroes(104, "Legion Commander")
    object Techies: Heroes(105, "Techies")
    object EmberSpirit: Heroes(106, "Ember Spirit")
    object EarthSpirit: Heroes(107, "Earth Spirit")
    object Underlord: Heroes(108, "Underlord")
    object Terrorblade: Heroes(109, "Terrorblade")
    object Phoenix: Heroes(110, "Phoenix")
    object Oracle: Heroes(111, "Oracle")
    object WinterWyvern: Heroes(112, "Winter Wyvern")
    object ArcWarden: Heroes(113, "Arc Warden")
    object MonkeyKing: Heroes(114, "Monkey King")
    object DarkWillow: Heroes(119, "Dark Willow")
    object Pangolier: Heroes(120, "Pangolier")
    object Grimstroke: Heroes(121, "Grimstroke")
    object Hoodwink: Heroes(123, "Hoodwink")
    object VoidSpirit: Heroes(126, "Void Spirit")
    object Snapfire: Heroes(128, "Snapfire")
    object Mars: Heroes(129, "Mars")
    object Ringmaster: Heroes(131, "Ringmaster")
    object Dawnbreaker: Heroes(135, "Dawnbreaker")
    object Marci: Heroes(136, "Marci")
    object PrimalBeast: Heroes(137, "Primal Beast")
    object Muerta: Heroes(138, "Muerta")
    object Kez: Heroes(145, "Kez")
}